Question 2 By Borna Maherani ID = 401243079

تابع اول محاسبه توان ان ام ماتریس در اردر ان می باشد. برای آنکه محاسبات ما با اعداد بزرگ نیز درست باشد تایپ ماتریس را فلوت قرار می دهیمن تا اورفلو احتمالی رخ ندهد.تعداد ضرب های ماتریسی در این الگوریتم از حد مجاز خواسته شده در سوال بالاتر نمی شود.
تابع دوم پیاده سازی توان ان ام از روی مقادیر ویژه و بردار های ویژه ماتریس می باشد. برای محاسبه توان ان ام یک ماتریس میتوان اول ماتریس را به فرم قطری آن در آورد و سپس با استفاده از ماتریس را به توان اعداد بزرگ رساند. درین الگوریتم از ضرب ماتریسی کمتری استفاده می شود. ماتریس دی فرم قطری ماتری آ می باشد.
در نهایت با به دست آوردن توان ان ام میتوان جمله ان ام دنباله فیبوناچی را به دست آورد

In [12]:
import numpy as np
import math

A = np.array([
    [1, 1],
    [1, 0]
], dtype=np.float64)


def fib_from_A(A, n):
    if n == 1:
        return A
    else:
        P = fib_from_A(A,math.floor(n/2))
        if n % 2 == 0:
            return np.matmul(P,P)
        else:
            return np.matmul(np.matmul(P,P),A)
    
    
def fib_from_eig(A,n):
    w, v = np.linalg.eig(A)
    temp1 = 1/v[1][0]
    temp2 = 1/v[1][1]
    v = np.transpose(v)
    v[:][0] *= temp1
    v[:][1] *= temp2
    v = np.transpose(v)
    vInv = np.linalg.inv(v)
    D = np.matmul(np.matmul(vInv,A),v)
    Z = np.copy(D)
    Z[1][0] = 0
    Z[0][1] = 0
    Z[0][0] = Z[0][0] ** n
    Z[1][1] = Z[1][1] ** n
    return (np.matmul(np.matmul(v,Z),vInv))

print(fib_from_eig(A,7))
print(fib_from_A(A,7))

print(fib_from_eig(A,1234))
print(fib_from_A(A,1234))


[[21. 13.]
 [13.  8.]]
[[21. 13.]
 [13.  8.]]
[[5.62666043e+257 3.47746739e+257]
 [3.47746739e+257 2.14919304e+257]]
[[5.62666043e+257 3.47746739e+257]
 [3.47746739e+257 2.14919304e+257]]


در این بخش هر دو تابع را ۱۰۰۰ بار صدا مرده و مدت زمان اجرایی هر بخش را نشان می دهیم. برای توان رساندن نیاز به ان بار ضرب کردن می باشد ولی در الگوریتم اول این کار در زمان لوگ ان انجام مییشود که خیلی سریعتر می باشد.
نتایج به دست آمده مطابق انتظارات می باشد.

In [11]:

times = 10000

etime = np.testing.measure('fib_from_eig(A,1234)', times=times)

print("Time for 10000 execution : ", etime , "s")

times = 10000

etime = np.testing.measure('fib_from_A(A,1234)', times=times)

print("Time for 10000 execution : ", etime , "s")  

Time for 10000 execution :  0.63 s
Time for 10000 execution :  0.32 s
